[build-system]
requires = ["scikit-build-core==0.11.6", "pybind11==3.0.1"]
build-backend = "scikit_build_core.build"

[project]
name = "nrforge-ngap"
version = "0.1.0"
description = "Typed NGAP APER Python SDK backed by NRForge C++"
requires-python = ">=3.10"
license = {file = "LICENSE"}
readme = "README.md"

[tool.scikit-build]
cmake.build-type = ""
wheel.packages = ["src/nrforge_ngap"]
build-dir = "build/{wheel_tag}"
build.tool-args = ["-j2"]
install.strip = true
wheel.license-files = ["LICENSE", "PYBIND11-LICENSE"]
sdist.include = ["ngap_sdk/**", "src/**", "tests/**", "examples/**", "CMakeLists.txt", "README.md", "LICENSE", "PYBIND11-LICENSE"]
