if(NOT DEFINED NRFORGE_SOURCE_ROOT OR NOT DEFINED NRFORGE_GENERATED_ROOT)
  message(FATAL_ERROR "SDK verification requires source and generated roots")
endif()
include("${NRFORGE_GENERATED_ROOT}/sdk-lock.cmake")
set(expected_files "sdk-lock.cmake")
foreach(entry IN LISTS NRFORGE_GENERATED_HASHES)
  string(REPLACE "|" ";" pair "${entry}")
  list(GET pair 0 relative)
  list(APPEND expected_files "${relative}")
endforeach()
file(GLOB_RECURSE current_files LIST_DIRECTORIES FALSE
  RELATIVE "${NRFORGE_GENERATED_ROOT}" "${NRFORGE_GENERATED_ROOT}/*")
list(SORT expected_files)
list(SORT current_files)
if(NOT current_files STREQUAL expected_files)
  message(FATAL_ERROR "SDK generated file set differs from sealed snapshot")
endif()
foreach(scope IN ITEMS SOURCE GENERATED)
  if(scope STREQUAL "SOURCE")
    set(root "${NRFORGE_SOURCE_ROOT}")
  else()
    set(root "${NRFORGE_GENERATED_ROOT}")
  endif()
  foreach(entry IN LISTS NRFORGE_${scope}_HASHES)
    string(REPLACE "|" ";" pair "${entry}")
    list(GET pair 0 relative)
    list(GET pair 1 expected)
    if(NOT EXISTS "${root}/${relative}")
      message(FATAL_ERROR "Missing SDK ${scope} input: ${relative}")
    endif()
    file(SHA256 "${root}/${relative}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "SDK ${scope} fingerprint mismatch: ${relative}")
    endif()
  endforeach()
endforeach()
if(DEFINED NRFORGE_SDK_ARCHIVE)
  if(NOT EXISTS "${NRFORGE_SDK_RECEIPT}")
    message(FATAL_ERROR "SDK archive has no successful build receipt; build before install")
  endif()
  include("${NRFORGE_SDK_RECEIPT}")
  file(SHA256 "${NRFORGE_SDK_ARCHIVE}" actual_archive)
  if(NOT NRFORGE_BUILT_FINGERPRINT STREQUAL NRFORGE_SDK_FINGERPRINT OR
     NOT actual_archive STREQUAL NRFORGE_BUILT_ARCHIVE_SHA256)
    message(FATAL_ERROR "SDK archive differs from successful build receipt")
  endif()
endif()
